# Generated by Django 5.0.7 on 2024-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magus', '0002_profile_last_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_session',
            field=models.BooleanField(default=False),
        ),
    ]
